services:
  - type: web
    name: dotflow-client
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    httpPort: 3000
    healthCheckPath: /health
    minMemory: 256
    maxMemory: 512
    disk: 1024
    cpu: 1

  - type: web
    name: dotflow-server
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    httpPort: 3001
    healthCheckPath: /health
    minMemory: 256
    maxMemory: 512
    disk: 1024
    cpu: 1
